on:
  push:
    branches: master
  pull_request:
    branches: master


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: echo $GITHUB_ENV
      - run: echo "FROM=WORKFLOW" >> $GITHUB_ENV
      - run: echo $PATH
      - run: python check.py
      - run: echo $PATH
